catalogMode: prefer
minimumReleaseAgeExclude:
  - '@img/sharp-darwin-arm64@0.35.0'
  - '@img/sharp-darwin-x64@0.35.0'
  - '@img/sharp-freebsd-wasm32@0.35.0'
  - '@img/sharp-libvips-darwin-arm64@1.3.0'
  - '@img/sharp-libvips-darwin-x64@1.3.0'
  - '@img/sharp-libvips-linux-arm64@1.3.0'
  - '@img/sharp-libvips-linux-arm@1.3.0'
  - '@img/sharp-libvips-linux-ppc64@1.3.0'
  - '@img/sharp-libvips-linux-riscv64@1.3.0'
  - '@img/sharp-libvips-linux-s390x@1.3.0'
  - '@img/sharp-libvips-linux-x64@1.3.0'
  - '@img/sharp-libvips-linuxmusl-arm64@1.3.0'
  - '@img/sharp-libvips-linuxmusl-x64@1.3.0'
  - '@img/sharp-linux-arm64@0.35.0'
  - '@img/sharp-linux-arm@0.35.0'
  - '@img/sharp-linux-ppc64@0.35.0'
  - '@img/sharp-linux-riscv64@0.35.0'
  - '@img/sharp-linux-s390x@0.35.0'
  - '@img/sharp-linux-x64@0.35.0'
  - '@img/sharp-linuxmusl-arm64@0.35.0'
  - '@img/sharp-linuxmusl-x64@0.35.0'
  - '@img/sharp-wasm32@0.35.0'
  - '@img/sharp-webcontainers-wasm32@0.35.0'
  - '@img/sharp-win32-arm64@0.35.0'
  - '@img/sharp-win32-ia32@0.35.0'
  - '@img/sharp-win32-x64@0.35.0'
  - '@types/node@25.9.3'
  - sharp@0.35.0
  - nuxtseo-layer-devtools
  - nuxtseo-shared
  - '@vue/compiler-core@3.5.38'
  - '@vue/compiler-dom@3.5.38'
  - '@vue/compiler-sfc@3.5.38'
  - '@vue/compiler-ssr@3.5.38'
  - '@vue/reactivity@3.5.38'
  - '@vue/runtime-core@3.5.38'
  - '@vue/runtime-dom@3.5.38'
  - '@vue/server-renderer@3.5.38'
  - '@vue/shared@3.5.38'
  - vue@3.5.38
shellEmulator: true

trustPolicy: no-downgrade
packages:
  - '!examples/**'
  - '!test/compat-v2/**'

overrides:
  '@unhead/vue': ^3.1.3
  unhead: ^3.1.3
  vue: ^3.5.38
catalog:
  '@antfu/eslint-config': ^9.0.0
  '@nuxt/devtools-kit': 4.0.0-alpha.7
  '@nuxt/kit': ^4.4.8
  '@nuxt/module-builder': ^1.0.2
  '@nuxt/schema': ^4.4.8
  '@nuxt/test-utils': ^4.0.3
  '@nuxt/ui': ^4.8.2
  '@nuxtjs/i18n': ^10.4.0
  '@types/node': ^25.9.3
  '@unhead/bundler': ^3.1.3
  '@unhead/vue': ^3.1.3
  '@vue/test-utils': ^2.4.11
  bumpp: ^11.1.0
  case-police: ^2.2.1
  cheerio: ^1.2.0
  citty: ^0.2.2
  consola: ^3.4.2
  defu: ^6.1.7
  escape-string-regexp: ^5.0.0
  eslint: ^10.4.1
  eslint-plugin-harlanzw: ^0.17.0
  exsolve: ^1.0.8
  happy-dom: ^20.10.2
  image-size: ^2.0.2
  lint-staged: ^17.0.7
  markdownlint-cli: ^0.48.0
  nuxt: ^4.4.8
  nuxt-security: ^2.6.0
  nuxt-site-config: ^4.1.0
  nuxtseo-layer-devtools: ^5.3.0
  nuxtseo-shared: ^5.3.0
  pathe: ^2.0.3
  pkg-types: ^2.3.1
  playwright-core: ^1.60.0
  sass: ^1.100.0
  scule: ^1.3.0
  semver: ^7.8.4
  sharp: ^0.35.0
  sirv: ^3.0.2
  tinyglobby: ^0.2.17
  typescript: ^6.0.3
  ufo: ^1.6.4
  ultrahtml: ^1.6.0
  unbuild: ^3.6.1
  unhead: ^3.1.3
  vitest: ^4.1.8
  vue: ^3.5.38
  vue-tsc: ^3.3.4
ignoredBuiltDependencies:
  - esbuild
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
trustPolicyIgnoreAfter: 262800
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  vue-demi: true
