import type { Nuxt, NuxtTemplate } from '@nuxt/schema'

export interface PathsTemplateContext {
  nuxt: Nuxt
  options: {
    getPaths: () => Promise<Record<'public', string[]>>
  }
}

export const headTypeTemplate: NuxtTemplate<PathsTemplateContext> = {
  filename: 'head.d.ts',
  getContents: async ({ options }) => {
    const paths = await options.getPaths()

    let output = '// Generated by path discovery\n'

    output += `
declare module '#app/nuxt' {
  import { HeadEntry, HeadTag } from '@vueuse/head'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}

type PublicFiles = ${paths.public.map(path => `'/${path}'`).join('|')} | string

declare module '@nuxt/schema' {
  interface HeadAugmentations {
    link: {
      href: PublicFiles
    }
    script: {
      src: PublicFiles
    }
  }
}
`
    return output
  },
}
