import type { Nuxt, NuxtTemplate } from '@nuxt/schema'

export interface PathsTemplateContext {
  nuxt: Nuxt
  options: {
    getPaths: () => Promise<Record<'public', string[]>>
  }
}

export const headTypeTemplate: NuxtTemplate<PathsTemplateContext> = {
  filename: 'head.d.ts',
  getContents: async ({ options }) => {
    const paths = await options.getPaths()

    let output = '// Generated by path discovery\n'
    if (paths.public.length)
      output += `export type PublicFiles = ${paths.public.map(path => `'/${path}'`).join('|')}\n`

    output += `
module '#app/nuxt' {
  import { HeadEntry, HeadTag } from '@vueuse/head'

  interface RuntimeNuxtHooks {
    'head:tags': (tag: HeadTag[]) => Promise<void> | void
    'head:entries': (entries: HeadEntry[]) => Promise<void> | void
  }
}

module '@nuxt/schema' {
  import { VueUseHeadSchema } from '@vueuse/head'
  import { MergeHead } from '@zhead/schema'
  import { ReactiveHead } from '@zhead/schema-vue'

  export interface HeadAugmentations extends MergeHead {
    link: {
      href: PublicFiles
    }
    script: {
      src: PublicFiles
    }
  }

  export interface MetaObject {
    /**
     * The character encoding in which the document is encoded => \`<meta charset="<value>" />\`
     *
     * @default \`'utf-8'\`
     */
    charset?: string;
    /**
     * Configuration of the viewport (the area of the window in which web content can be seen),
     * mapped to => \`<meta name="viewport" content="<value>" />\`
     *
     * @default \`'width=device-width, initial-scale=1'\`
     */
    viewport?: string;
        /**
     * The <title> HTML element defines the document's title that is shown in a browser's title bar or a page's tab.
     * It only contains text; tags within the element are ignored.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/title
     */
    title?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['title'];
    /**
     * Generate the title from a template.
     */
    titleTemplate?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['titleTemplate'];
    /**
     * The <base> HTML element specifies the base URL to use for all relative URLs in a document.
     * There can be only one <base> element in a document.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
     */
    base?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['base'];
    /**
     * The <link> HTML element specifies relationships between the current document and an external resource.
     * This element is most commonly used to link to stylesheets, but is also used to establish site icons
     * (both "favicon" style icons and icons for the home screen and apps on mobile devices) among other things.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#attr-as
     */
    link?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['link'];
    /**
     * The <meta> element represents metadata that cannot be expressed in other HTML elements, like <link> or <script>.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
     */
    meta?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['meta'];
    /**
     * The <style> HTML element contains style information for a document, or part of a document.
     * It contains CSS, which is applied to the contents of the document containing the <style> element.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/style
     */
    style?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['style'];
    /**
     * The <script> HTML element is used to embed executable code or data; this is typically used to embed or refer to JavaScript code.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script
     */
    script?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['script'];
    /**
     * The <noscript> HTML element defines a section of HTML to be inserted if a script type on the page is unsupported
     * or if scripting is currently turned off in the browser.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript
     */
    noscript?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['noscript'];
    /**
     * Attributes for the <html> HTML element.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html
     */
    htmlAttrs?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['htmlAttrs'];
    /**
     * Attributes for the <body> HTML element.
     *
     * @see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/body
     */
    bodyAttrs?: ReactiveHead<HeadAugmentations & VueUseHeadSchema>['bodyAttrs'];
  }
}
`
    return output
  },
}
