name: Test

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  lint-typecheck:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm i

      - name: Prepare
        run: pnpm run dev:prepare

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

      - name: Typecheck
        run: pnpm run typecheck

  test:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v6
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm i

      - name: Prepare
        run: pnpm run dev:prepare

      - name: Build
        run: pnpm run build

      - name: Test
        run: pnpm test:run
